openapi: 3.1.0
components:
  schemas:
    newUser:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    user:
      allOf:
        - $ref: '#/components/schemas/newUser'
        - type: object
          required:
            - id
          properties:
            id:
              type: number
    users:
      type: array
      items:
        $ref: '#/components/schemas/user'
examples:
  user:
    id: 1
    name: Alisdair
  users:
    - id: 1
      name: Adam
    - id: 2
      name: Betty
    - id: 3
      name: Calvin
